apiVersion: v1 #define the api version of the resource
kind: Service #define the kind of resource, in this case a Service
metadata: 
  name: devsecops-demo-service # define the name of the service to provide access to the application even though IP addresses may change 
  namespace: default # define the namespace in which the service will be created
  labels: # define the labels for the service, which can be used for selection and organization
    app.kubernetes.io/name: devsecops-demo-app # define the name of the application associated with the service
spec: # define the specification of the service, including its type, selector, and ports
  type: ClusterIP # define the type of service, in this case a ClusterIP service that exposes the application on a cluster-internal IP
  selector: # define the selector for the service, which determines which pods will receive traffic from the service
    app: devsecops-demo-app # define the label selector for the service, which matches the label of the pods created by the deployment
  ports:
    - name: http # define the name of the port for the service
      port: 80 # define the port on which the service will be exposed
      targetPort: 5000 # define the port on which the application is running in the container, which will receive traffic from the service
      protocol: TCP 
      