import os
import json
import requests
from google import genai


GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]

def read_findings():
    """Reads issues from SARIF files generated by Bandit and Trivy."""
    findings = []
    for filename in ["bandit-results.sarif", "trivy-results.sarif"]:
        if os.path.exists(filename):
            with open(filename) as f:
                data = json.load(f)
                for run in data.get("runs", []):
                    for result in run.get("results", []):
                        findings.append({
                            "tool": run.get("tool", {}).get("driver", {}).get("name", "unknown"),
                            "message": result.get("message", {}).get("text", ""),
                            "rule": result.get("ruleId", "")
                        })
    return findings

def build_prompt(findings):
    findings_text = "\n".join(
        f"- [{f['tool']}] {f['rule']}: {f['message']}" for f in findings
    )
    return f"""You are a security triage assistant. Below are automated scan findings 
from a CI/CD pipeline. For each, briefly assess: 1- likely severity/priority, 
2- whether it looks like a real risk or possible false positive, 3- one-line 
suggested next step. Keep the whole response between 50-300 words.

Findings:
{findings_text}
"""

def call_gemini(prompt):
    try:
        client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
        )
        
        
        return response.text
    except Exception as e:
        print(f"Error calling Gemini API: {e}")
        return "Error generating summary."

def main():
    findings = read_findings()
    if not findings:
        print("No findings to triage.")
        with open("ai_triage_summary.md", "w", encoding="utf-8") as f:
            f.write("### AI Security Triage\n\nNo security findings detected in this run. All gates are clear.")
        return
    prompt = build_prompt(findings)
    summary = call_gemini(prompt)
    with open("ai_triage_summary.md", "w") as f:
        f.write("##  Triage Summary\n\n" + summary)

if __name__ == "__main__":
    main()