name: DevSecOps Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_scans:
    name: Security Scanning Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      # 1. SAST (Bandit)
      - name: Run Bandit (SAST Scan)
        run: |
          echo "=== Running Bandit SAST Scanner ==="
          bandit -r .

      # 2. Secret Scanning (Trufflehog)
      - name: Secret Scanning (Trufflehog)
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified

      # 3. Compile Docker image  (Build)
      - name: Build Docker Image
        run: |
          docker build -t devsecops-demo-app:latest .

      # 4. Dependency Scanning (Trivy)
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-demo-app:latest'
          format: 'table'
          exit-code: '0' # Şimdilik raporu görmek için 0 kalsın, kritik bulguda fail etmek istersek '1' yaparız.
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
