name: DevSecOps Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write # SARIF raporlarını GitHub Security tabına yazma izni


jobs:
  security_scans:
    name: Security Scanning Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit bandit-sarif-formatter
          
      - name: Run Bandit (SAST Scan)
        run: |
          echo "=== Running Bandit SAST Scanner ==="
          bandit -r . -f sarif -o bandit-results.sarif

      - name: Upload Bandit SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'bandit-results.sarif'
          category: 'bandit-sast'

      # #Secret Scanning (Trufflehog)
      - name: Secret Scanning (Trufflehog)
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified

      #  Compile Docker Image
      - name: Build Docker Image
        run: |
            docker build --no-cache -t devsecops-demo-app:latest .

      - name: Check installed Python packages
        run: |
            docker run --rm devsecops-demo-app:latest python -c "import msgpack, setuptools; print('msgpack:', msgpack.__version__); print('setuptools:', setuptools.__version__)"
      

      #  Container Security (Trivy)
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-demo-app:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
        env:
          TRIVY_NO_CACHE: 'true'
          #scanners: 'vuln'
      - name: Debug Trivy SARIF
        if: always()
        run: |
          echo "=== msgpack ==="
          grep -i -A 15 -B 5 "msgpack" trivy-results.sarif || true
          echo "=== setuptools ==="
          grep -i -A 15 -B 5 "setuptools" trivy-results.sarif || true
          
      - name: Debug - Trivy Human Readable Output
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-demo-app:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          #scanners: 'vuln'

      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('trivy-results.sarif') != ''
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-container'

      #  Deploy the application in a container for DAST
      - name: Run Container for DAST
        run: |
          docker run -d --name test-app -p 5000:5000 devsecops-demo-app:latest
          sleep 5
      #  DAST (OWASP ZAP Baseline Scan)
      - name: OWASP ZAP Full Scan
        run: |
          mkdir -p zap_out
          chmod 777 zap_out
          docker run --net=host -v $(pwd)/zap_out:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t "http://localhost:5000/go?url=test" \
            -r zap_report.html \
            -J zap_report.json || true

          cp zap_out/zap_report.* . || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always() # ensure the report is uploaded even if the scan fails
        with:
          name: zap-scan-report
          path: |
            zap_report.html
            zap_report.json
      #  Stop and Remove the Container
      - name: Stop and Remove Container
        if: always()
        run: |
          docker stop test-app || true
          docker rm test-app   || true